### ISSUE TITLE
Add support for Waveshare 2.13" display

### ISSUE THREAD

**Issue by chrisys** [balenalabs/inkyshot#13]
https://www.waveshare.com/wiki/2.13inch_e-Paper_HAT

**Comment by lmatter** [comment]
I'm currently working on this

**Comment by lmatter** [comment]
I have it working.  Main issue is that epd.width and epd.height are reversed from what you would expect.  Margins also didn't work so I changed test_character to 'w' for now.  https://imgur.com/22VgvJi

**Comment by chrisys** [comment]
@lmatter nice work! If you want to share a draft PR I may be able to help with some of the margins stuff - the waveshare 'v2' display is a slightly higher resolution than the Pimoroni one so that may be complicating things too.

**Comment by lmatter** [comment]
I'll put it together this weekend.  Right now it's a "duck taped" mess.  I will try to parameterize the differences with Inky and Waveshare.  

There's still the matter of the case not fitting.  Since the ribbon cable is on the other side (so not on the same side as the SD card) the second case model needs to be widened unless you just use the on-board usb port for power.  Otherwise it kinda works to put the pi zero in upside down and cut a hole on the other side of the front for USB  (which I also hacked in tinkercad but no round corners).

**Comment by lmatter** [comment]
@chrisys I'm unable to log into balena-dev concourse to fix the PR blocker (I get a 404 when trying to authenticate via github).  Any assist would be appreciated

**Comment by chrisys** [comment]
@lmatter it'll be the commit message, apologies we haven't detailed this in the repo yet but something like the below will allow it to pass:

```
Your change

Change-type: minor
Signed-off-by: Your Name <your@email.io>
```

I'm working on the PR right now, it's not working for the Inky display so I'll have some changes for sure, but I'll push them straight to your branch so we can get both working simultaneously.

**Comment by chrisys** [comment]
@lmatter I updated the commit message on your behalf and merged everything, it should be good for both displays now but if there are any problems let me know! Thanks for the contribution to the project!

**Comment by lmatter** [comment]
@chrisys Thanks for merging it!  I have verified it worked for me and I'm digging the Balena cloud (I'm now going to work on multi-room audio). 
I was actually able to jam it in the [second case design](https://imgur.com/qSuYlak) with the USB in the rear even with the SD card, but it was a tight fit.

**Comment by chrisys** [comment]
@lmatter nice one! Loving the filament colour you picked there 😄

**Comment by chrisys** [comment]
@hacked-robot you would have to deploy the code again to get the latest version, then add the environment variable, but that's it!

The update workflow is clunky right now but we're working on it as we speak. To update just click the `deploy with balena` button again, create a new app with the updated version of Inkyshot, and then move your existing device from your old app to the new one within the dashboard. No need to flash SD cards or anything. In the future we'll be adding the functionality so clicking deploy again will allow you to update an existing app. If you still have trouble after that post a thread on our support forums and we'll figure it out.

**Comment by catt-tung** [comment]
@lmatter OMG that case color!! Amazing stuff thanks so much for contributing to supporting the waveshare display! Thanks @chrisys for code review :))

**Comment by lmatter** [comment]
@catt-tung Thanks for the comments!  The filament came from [this assortment](https://www.amazon.com/gp/product/B07RNM7LLB) - I love the colors and almost always use these.  Exception would be when I use a color changing filament.    Great project!

**Comment by chrisys** [comment]
Hey @hacked-robot et al, I just wanted to ping you again to let you know that balenaCloud has now been updated so when you click the deploy button there's now an option to select an existing application and update that instead. No need to juggle devices anymore. 👍
