### ISSUE TITLE
Allow selection of quote category

### ISSUE THREAD

**Issue by chrisys** [balenalabs/inkyshot#18]
The quotes.rest API offers alternative categories, the default is `inspire` but we have the following options. Could also randomise the category on our end.

      "inspire": "Inspiring Quote of the day",
      "management": "Management Quote of the day",
      "sports": "Sports Quote of the day",
      "life": "Quote of the day about life",
      "funny": "Funny Quote of the day",
      "love": "Quote of the day about Love",
      "art": "Art quote of the day ",
      "students": "Quote of the day for students"

**Comment by huckleberry914** [comment]
Would love to see this implemented as an Environment Variable, so that those of us who are new to coding (and to Balena deployments) could switch categories without having to dig into the code. Been having fun playing around with it so far, and would love this option!!
