### ISSUE TITLE
Update documentation to mention which screws that is used for the V2 case

### ISSUE THREAD

**Issue by smi73** [balenalabs/inkyshot#20]
Hello
Awsome project. I have build one myself and really like the V2 case. It could be good to update the documentation with info about which screws that is used in the V2 case. I could ofcourse try to experiment with the screws, but I have to order them and would like to order the right one :).
Thanks again for an awsome project.

**Comment by andreas-metaxas** [comment]
Hello smi73,
Thanks for the feedback. We in balena enjoyed it too, it was a cool and fun project.
So the screws that I used are No.2 (2.2) x 1/2 inch (12.5) Torx self. I will add a link here for you also.
https://www.accu.co.uk/en/self-tapping-raised-torx-screws/21738-SHRKT-No-2-1-2-A2
If anything else please feel free to notify us.
