### ISSUE TITLE
Inky display not updated

### ISSUE THREAD

**Issue by Richard238** [balenalabs/inkyshot#26]
Inky phat display not changed, either with quote of the day, or a manual message.
This is on a Pi Zero with a fresh Balena OS install.

Also, I notice the code is set for Inky BLACK.
`display = InkyPHAT("black")`  I'm new to Balena, so without SFTP/Desktop access, how do I change it for my YELLOW Inkyphat?

Thank you!

**Comment by gelbal** [comment]
Hey @Richard238, I'm a member of the balena team and I am familiar with the inkyshot code. I'm running the inkyshot code on my Red Inkyphat and it runs totally fine (although I don't see any red color as inkyshot code base uses only black and white color at the moment. Actually it'd be great for inkyshot to support red/yellow/other colors). 

I suspect that your device has another issue. Could you please open a thread at [the balena forums](https://forums.balena.io/)? 

Balena support team could help you troubleshoot the issue and even connect to your device to check out the logs (if you provide support access to your device).

**Comment by Richard238** [comment]
I was rather hoping to avoid creating yet another forum login, but, it's done.
[Link](https://forums.balena.io/t/inkyshot-nothing-showing-on-display/198149)

Thanks,
Richard.

**Comment by chrisys** [comment]
Root cause here is that there seems to be a new hardware revision of the InkyPHAT which, although higher resolution, requires an updated version of the library. I've updated the libs and altered the code to autodetect both versions.
