### ISSUE TITLE
Quote and weather rotation does not work

### ISSUE THREAD

**Issue by gelbal** [balenalabs/inkyshot#30]
https://forums.balena.io/t/inkyshot-variables-not-working/203394

**Comment by manuelemac** [comment]
_fast fix_ 

- **default** --> quote only.
- **ALTERNATE_FREQUENCY** set --> switch between quote/weather
- **DISPLAY_QUOTE** = 0 --> showing only weather

substitute the last block of code in update_display.py after the comment
# Alternate to other display code

```
if "DISPLAY_QUOTE" in os.environ and os.environ["DISPLAY_QUOTE"]=='0':
        os.environ["NEXT_DISPLAY"] = 'weather'
else:
        if(NEXT_DISPLAY == 'quote' and "ALTERNATE_FREQUENCY" in os.environ): 
            os.environ["NEXT_DISPLAY"] = 'weather'
        else :
            os.environ["NEXT_DISPLAY"] = 'quote'

```

**Comment by gelbal** [comment]
Hey @manuelemac thanks for chiming in. Would you like to open a pull request with your solution? 

Then we could test it out and merge it once we confirm that this solves the issue.
