### ISSUE TITLE
Inkyshot-offline

### ISSUE THREAD

**Issue by andreas-metaxas** [balenalabs/inkyshot#31]
It seems to be working for 2 or 3 days and after that is offline for no particular reason, till I unplug it and plug it right in.

**Comment by chrisys** [comment]
I'm going to close this one now it as I don't think it can be an issue with this app, but anyone feel free to re-open if it's an ongoing issue!

**Comment by klutchell** [comment]
I'm seeing this too. If it disconnects from my wifi for whatever reason it will switch to Wifi Connect broadcast mode and not reconnect on it's own unless I reboot, or hit the Wifi Connect portal. Should we add an override to disable Wifi-Connect if we are confident the network will return?

**Comment by gelbal** [comment]
Good idea @klutchell. I remember seeing a user on the forums asking to disable WiFi Connect as well.

**Comment by klutchell** [comment]
This should probably actually be a feature request for the wifi-connect repo, since there are a lot of related issues over there.

**Comment by gelbal** [comment]
Good point. The following issues are related:
https://github.com/balena-os/wifi-connect/issues/274
https://github.com/balena-os/wifi-connect/issues/378
