### ISSUE TITLE
Weather info is sometimes not displayed

### ISSUE THREAD

**Issue by gelbal** [balenalabs/inkyshot#34]
In the logs I see:
```
04.12.20 09:58:14 (+0100)  main  INFO:root:Retrieving weather forecast
04.12.20 09:58:14 (+0100)  main  ERROR:root:HTTP Error 403: Forbidden
```
We need to understand why this happens and workaround 403 issues.

**Comment by Ereski** [comment]
I'm having the same issue. I tried CURLing the logged URL from inside the container and I get a response just fine.

**Comment by manuelemac** [comment]
same here

**Comment by gelbal** [comment]
I figured out the problem here. Weather API that Inkyshot uses started applying restrictions on the calls. Quote from the weather API provider [here](https://api.met.no/blog/2020-06-12-locfc2)

> You must identify yourself with contact information in the User-Agent request header. Whereas requests without any such header or just a generic string (e.g. "okhttp/3.12.4") until now has been throttled, new products will return a 403 Forbidden instead.

Fixing it by adding a user agent to the API calls.
