### ISSUE TITLE
INKY_MESSAGE var is broken.

### ISSUE THREAD

**Issue by theodonal** [balenalabs/inkyshot#41]
Hey, 

ran into an issue were adding the env var of "INKY_MESSAGE" actually doesn't work in the current code for "update-display.py"

between line 340 and 341 the following code needs to be added to make this work. 

`elif message is not None:
        pass
`
The way the current code works the custom message is over written by the qoute making the option for override not work. 

its xmas tomorrow and I am tired so will make the changes and send to you over some time next week.

**Comment by gelbal** [comment]
Thanks for reporting this @theodonal. You are right. I'm pushing a fix now.
