### ISSUE TITLE
Allow pixel font to be font_selected

### ISSUE THREAD

**Issue by catt-tung** [balenalabs/inkyshot#6]
Currently have the pixel font for readability for long quotes, wanting to get it as one of the fonts we can choose to display as well

**Comment by chrisys** [comment]
We can workaround this for now by setting font size to 8, then it will always use the pixel font, but of course this doesn't let you use the pixel font in a larger size.

**Comment by SamEureka** [comment]
I was able to select the pixel font by adding `Grand9KPixel = "/usr/app/fonts/Grand9KPixel.ttf"` just below the font import statements in update-display.py. Then you declare `Grand9KPixel` as the value for the `FONT` Device Variable. Let me know if you want this in form of a PR.

**Comment by catt-tung** [comment]
Thanks for adding this @SamEureka! Much appreciated
