### ISSUE TITLE
Case designs.

### ISSUE THREAD

**Issue by Richard238** [balenalabs/inkyshot#63]
Hi,

Looking at the case design files, what is the difference between case-design1 and case-design2?

Thank you.

**Comment by Mahir-Isikli** [comment]
Hi, having the same question. Did you figure or test it out by any chance?

Thanks.

**Comment by chrisys** [comment]
<img width="1189" alt="Screenshot 2021-12-21 at 11 11 39" src="https://user-images.githubusercontent.com/521698/146920695-3394ae2a-f5da-473c-8edc-038e237ca956.png">

They are different in appearance - you can use the preview function on GitHub to look at the 3D models and compare them. Ultimately both do the same job, it's a question of personal preference as to which design you prefer. I hope this helps - closing for now.
